### ISSUE TITLE
OVH manager has wrong size of mysql database password. 30 instead of 12.

### ISSUE THREAD

**Issue by pascalheraud** [ovh-ux/ovh-manager-web#205]
### Description

OVH manager has wrong size of mysql database password. 30 instead of 12.

### Steps to Reproduce

1. Update the password of a private database
2. Type a password containing 30 chars in first field

**Expected behavior:**

It should be accepted but it's refused (seems max size 12 chars).
The form should say it's 12 chars max or it should accept 30 chars.

**Actual behavior:**

30 chars is refused.

**Reproduces how often:**
Every time

**Comment by rfougier** [comment]
Hi, thank you for your report.
This problem has recently been solved.
Best regards.

**Comment by rfougier** [comment]
#189
