### ISSUE TITLE
permit login even without referrer

### ISSUE THREAD

**Issue by Dan33l** [ovh-ux/ovh-manager-web#403]
### Description

If a user agent (aka browser) does not transmit referer (with firefox setting [network.http.sendRefererHeader](http://kb.mozillazine.org/Network.http.sendRefererHeader) ), it is impossible to log into manager.

### Steps to Reproduce

1. Open Firefox and type `about:config` in the address bar and press "*Enter*".
2. If prompted with a warning, select "*I accept the risk!*"
3. Find the entry that says `network.http.sendRefererHeader` and double-click on it.
4. Set the entry to 2 : Disable referrer.
5. Restart firefox
6. Go to https://www.ovh.com/auth/?action=gotomanager, provide your credentials

**Expected behavior:**

I expect to be logged in.

**Actual behavior:**

I receive mail with title "Notification de connexion à votre compte", but after a while i am routed to the login page without being logged in.

**Reproduces how often:**

each time reproduced.

### Additional Information

[Personnal or sensitive data leak](https://blog.mozilla.org/security/2018/01/31/preventing-data-leaks-by-stripping-path-information-in-http-referrers/)

**Comment by Dan33l** [comment]
As work around, it is possible to set `network.http.referer.XOriginPolicy` to `1`. It permits to send a referrer only when the base domains are the same.

[Details about referrer settings](https://wiki.mozilla.org/Security/Referrer) with firefox.

**Comment by Dan33l** [comment]
The RFC does not require the referrer as mandatory.

**Comment by euhmeuh** [comment]
Hello there and thanks for spotting this!
As my colleague @Alkorin was saying, it seems like the referrer is currently used in the authentication process.
We'll see if we can adapt or improve this.
In the mean time, like you said, you could just setup the `XOriginPolicy` to `1` so that your browser only sends the Referrer to the same domain.
Thank you for taking the time to file this issue. We'll keep you updated :+1:

**Comment by euhmeuh** [comment]
After checking with the backend team, it appears that effectively, the Referrer field is actively used in our authentication process, and unfortunately cannot be changed.
I close this issue now and advocate anyone concerned of leaking sensitive data to use the `network.http.referer.XOriginPolicy` option in Firefox (or any similar option in another browser) to prevent the Referer from being passed across domains.
Sorry for the inconvenience.
