### ISSUE TITLE
Problème make install 

### ISSUE THREAD

**Issue by kiozix** [ovh-ux/ovh-manager-web#483]
### Description
j'ai un problème d'installation du manager web

### Steps to Reproduce

la machine est une unbuntu 14.04 TLS

j'ai effectuer les update

j'ai ensuite suivie le Readme

puis en fessant make install

je reçois ça comme erreur 

https://community.ovh.com/uploads/default/original/2X/9/91ad06ec85994a2c9a2806f9ac002faa8c7436ac.png

quel est le problème ?

**Comment by FredericEspiau** [comment]
Hello @kiozix !

Thank you for your question 👍 

As you can read in the https://github.com/ovh-ux/ovh-manager-web/blob/master/package.json file, we target Node 8 or newer. According to your image, you use v4.2.6.

Please update your NodeJS instance before trying to install the Web Manager 😃 . Don't hesitate to keep us updated about your progress !

**Comment by kiozix** [comment]
merci j'ai mis à jour nodejs avec les commande suivante

sudo npm cache clean -f
sudo npm install -g n
sudo n stable
sudo n latest

mais j'ai encore une erreur voir image http://prntscr.com/kdkuje

**Comment by kiozix** [comment]
yes

**Comment by kiozix** [comment]
j'ai un autre problème quel distribution vous me conseillerait pour ne plus avoir de problème

**Comment by antleblanc** [comment]
@kiozix 

We don't encourage you to install the manager as a `root` user.
That's the  reason why your screenshot say: `Cannot be run with sudo`.

We don't require any specific GNU/Linux distributions. 

I'm personally a huge fan of [Node Version Manager](https://github.com/creationix/nvm)
(Simple bash script to manage multiple active node.js versions).

Hope its help you.

---

Nous ne vous encourageons pas à installer l'espace client en tant qu'utilisateur `root`.
Raison pour laquelle votre capture d'écran dit: `Ne peut pas être exécuté avec sudo`.

Nous n'exigeons aucune GNU/Linux distribution spécifique.

Je suis personnellement un grand fan de [Node Version Manager](https://github.com/creationix/nvm)
(Script bash pour gérer plusieurs versions actives de node.js).

J'espère que cela vous aidera.

**Comment by kiozix** [comment]
je dois être en utilisateur kiozix et lancer sudo make install du coups ?

**Comment by kiozix** [comment]
ok tout est bon pour l'installation quand je lance il mets ça 
![image](https://user-images.githubusercontent.com/31328799/43775810-42bad97e-9a4e-11e8-9db9-284f388bc4ca.png)

**Comment by antleblanc** [comment]
@kiozix 
Could you try:

```sh
$ make clean
$ yarn cache clean
$ make install
$ make dev
```

**Comment by kiozix** [comment]
V10.8.0

Et même problème

**Comment by antleblanc** [comment]
@kiozix 

Instead of running `$ yarn cache clean`, can you test with: `$ npm cache clean -f` once again?
Sorry but for now the Web Manager isn't upgraded to only use Yarn.

I tried to reproduce your development environment and as you can see on my screenshots, everything looks good:
![screenshot_1](https://user-images.githubusercontent.com/428384/43799333-8b09476c-9a8d-11e8-9c2d-e4974d6b185e.png)

![screenshot_2](https://user-images.githubusercontent.com/428384/43799340-8de80752-9a8d-11e8-931e-9675025af1cd.png)

Have you tried [NVM](https://github.com/creationix/nvm)?

I have use specifically this command:
```sh
$ nvm install 10.8.0
$ nvm alias default 10.8.0
```

Hope it helps you!

**Comment by kiozix** [comment]
Thx you its work 
![image](https://user-images.githubusercontent.com/31328799/43802596-8ef34a90-9a96-11e8-9a79-d26a0d5ff747.png)
