### ISSUE TITLE
IPv6 DynHost

### ISSUE THREAD

**Issue by pacien** [ovh-ux/ovh-manager-web#554]
### Description

DynHost doesn't seem to accept IPv6 addresses.

### Steps to Reproduce

1. Create a DynHost for a domain using the web UI
2. Put an IPv6 address

**Expected behavior:**
Input should be accepted and a corresponding AAAA record should be created.

**Actual behavior:**
Input is refused.

**Reproduces how often:**
100% of the time

### Additional Information

_none_

**Comment by fchabrolle** [comment]
@pacien A valid address IPv4 is required by the API (IPv6 isn't handle yet).

**Comment by antleblanc** [comment]
Thanks @fchabrolle for your feedback.

**Comment by pacien** [comment]
Additional argument: some ISPs (such as Orange in France, Swisscom in Switzerland) derive IPv6 prefixes from the dynamically allocated IPv4 address, making IPv6 addresses unstable as well. Support for IPv6 DynHost by the API would greatly help to cope with this madness.
