### ISSUE TITLE
DNS SPF entry validation does not accept a ip subnet masks

### ISSUE THREAD

**Issue by LeoWinterDE** [ovh-ux/ovh-manager-web#584]
### Description
Adding a new SPF DNS entry with a [ip4 or ip6 mechanisms](http://www.openspf.org/SPF_Record_Syntax#ip4) does not accept a subnet mask.

### Steps to Reproduce
Try to add a new SPF DNS record and add a v4 or v6 ipaddress with a subnet mask, like 192.168.0.1/16.

![screenshot_2018-10-02 your ovh web control panel](https://user-images.githubusercontent.com/1300141/46346978-3bebf880-c64a-11e8-9373-48e8fe8233d4.png)

**Expected behavior:**
Accept entries with a valid subnet mask, for example: ipv4 /16, /28 or for ipv6 /96 ...

**Actual behavior:**
The validation is just wrong.

**Reproduces how often:**
Everytime.

**Comment by FredericEspiau** [comment]
Internal reference: MANAGER-1383

**Comment by FredericEspiau** [comment]
Should be fixed by #588

**Comment by LeoWinterDE** [comment]
This issue has been fixed, thanks.
