### ISSUE TITLE
Missing support for the new 'CAA' DNS zone record

### ISSUE THREAD

**Issue by cghislai** [ovh-ux/ovh-manager-web#95]
### Description
RFC 6844  https://tools.ietf.org/html/rfc6844 has been approved by the CA/Browser forum. It is effective since September 8th 2017 (https://cabforum.org/pipermail/public/2017-March/009917.html), yet there is no way for a CA to check the CAA dns record of ovh domains since we cannot add it using the current interface.

Source: https://blog.qualys.com/ssllabs/2017/03/13/caa-mandated-by-cabrowser-forum

### Steps to Reproduce
- Got to your domain zone
- Click add
** Expected behaviour **
CAA is listed. The validity of the value provided is checked before saving the dns record.

**Actual behavior:**
CAA is not listed.

**Comment by jleveugle** [comment]
Hello,

Thx for your feedback !

The manager use OVH API as our client, and this one doesn't provide CAA record at this moment. 

You can see it here : https://api.ovh.com/console/#/domain/zone/%7BzoneName%7D/record#POST

I will check this with the person who manage API and answer you asap :)

Have a good day

**Comment by jleveugle** [comment]
Hello,

CAA Dns records are now managed.

![capture d ecran 2018-03-15 a 14 38 28](https://user-images.githubusercontent.com/1357733/37466678-ae5bed60-285e-11e8-9701-9101be155e7c.png)

I invite you to test it and give us your feedback

See you !
